class Item {
  String imgpath;
  double price;
  String name;
  String Benefits;
  String Diseases_that_can_affect;
  String Treatment;
  Item({required this.name, required this.imgpath,required this.price,required this.Benefits, required this.Diseases_that_can_affect,required this.Treatment,});

}

final List<Item> items =[
  Item(name :"ارز صينى",imgpath:"asesst/imge/ارز صينى.jpg" , price: 1 ,Benefits :"Can grow well under harsh indoor conditions and low light. Also helps purify the air of toxins",Diseases_that_can_affect:"Drying out, root rot, tumor-likegrowths." , Treatment: "Regular watering, avoiding overlywet soil, and not over-caring for it." ),
  Item(name :"البامبو",imgpath:"asesst/imge/البامبو.jpg" , price: 2,Benefits :"Can tolerate harsh indoor conditions and can grow rapidly. Helps purify and improve indoor air quality.",Diseases_that_can_affect:"Drying out, mite infestations, funga diseases" , Treatment: "Regular watering, avoiding direct sunlight, ensuring good soil drainage. Also, natural insecticides can be used to control mites and fungal diseases."),
  Item(name :"الافوكادو",imgpath:"asesst/imge/نبات الافوكادو.jpg" , price: 3,Benefits :"Contains many vitamins and minerals essential for the body, and can be used in many culinary and beauty recipes.",Diseases_that_can_affect:"Drying out, black mold, and mite infestation." , Treatment: "Regular watering, reducing exposur to direct sunlight, and ensuring proper drainage." ),
  Item(name :"الالوا فيرا",imgpath:"asesst/imge/نبات الالوا فيرا.jpg" , price: 4,Benefits :"Contains a gel that can be used to treat burns, wounds, and renew skin. Also contains natural antibiotics that help fight infection. ",Diseases_that_can_affect:"Drying out, mite infestations, fungal diseases." , Treatment: "Regular watering, reducing exposure to direct sunlight, avoiding over-watering and over-fertilizing"),
  Item(name :"الاوركيد",imgpath:"asesst/imge/نبات الاوركيد.jpg" , price: 5,Benefits :"Contains antioxidants and can be used in many skincare and culinary recipes, and also adds beauty and fragrance to gardens.",Diseases_that_can_affect:"Black spot disease, powdery mildew, and aphid infestation." , Treatment: "Regular pruning and removal of infected leaves, providing good air circulation and avoiding overcrowding and using appropriate pesticides when necessary."),
  Item(name :"الزنجبيل",imgpath:"asesst/imge/نبات الزنجبيل.jpg" , price: 6,Benefits :"Contains antioxidants and many beneficial nutrients for health, and can be used in many medicinal and culinary recipes.",Diseases_that_can_affect:"Drying out, mite infestation, and root tumors." , Treatment: "Regular watering, avoiding exposureto overly wet soil, and providing good ventilation."),
  Item(name :"الزهرةالحمراء",imgpath:"asesst/imge/نبات الزهرة الحمراء.jpg" , price: 7,Benefits :"Contains vitamin E and antioxidants, and can be used in many culinary and skincare recipes, and also adds beauty to gardens.",Diseases_that_can_affect:"Gray mold, rust, and aphid infestation " , Treatment: "Regular pruning and removal of infected leaves, providing good air circulation and avoiding overcrowding, and using appropriate pesticides when necessary."),
  Item(name :"السرو",imgpath:"asesst/imge/نبات السرو.jpg" , price: 8,Benefits :"Can be an indoor or outdoor plant and can grow up to 30 meters in natural conditions. Helps purify the air of dust and pollutants.",Diseases_that_can_affect:"Mold, mite infestations, severe drying out." , Treatment: "Reducing watering, avoidingdirect sunlight, and cleaning the leaves regularly." ),
  Item(name :"الصبار",imgpath:"asesst/imge/نبات الصبار..png" , price: 9,Benefits :"Contains aloe vera gel which can be used to treat burns, wounds, and cleanse the skin, and also helps improve indoor air quality.",Diseases_that_can_affect:"Drying out, mite infestation, and fungal diseases." , Treatment: "Regular watering, reducing exposure to direct sunlight,and avoiding overwatering and over-fertilizing."),
  Item(name :"الكركديه",imgpath:"asesst/imge/نبات الكركديه.jpg" , price: 10,Benefits :"Contains compounds that promote digestive health and relieve headaches, and can be used in many culinary and medicinal recipes.",Diseases_that_can_affect:"Drying out, fungal diseases, and spider mite infestation." , Treatment: "Regular watering and ensuring proper drainage, providing good air circulation and avoiding overcrowding,and using appropriate pesticides when necessary."),
  Item(name :"الليفة",imgpath:"asesst/imge/نبات الليفة.jpg" , price: 11,Benefits :"Contains antioxidants and anti-inflammatory compounds, and can be used in many culinary recipes and as a natural insect repellent.",Diseases_that_can_affect:"Drying out, fungal diseases, and aphid infestation." , Treatment: "Regular watering and ensuring proper drainage, providing good air circulation and avoiding overcrowding,and using appropriate pesticides when necessary."),
  Item(name :"الليمون",imgpath:"asesst/imge/نبات الليمون.jpg" , price: 12,Benefits :"Contains vitamin C which helps improve immunity and prevent diseases, and can be used in many culinary recipes.",Diseases_that_can_affect:"Contains vitamin C which helps improve immunity and prevent diseases, and can be used in many culinary recipes." , Treatment: "Regular watering and ensuring properdrainage, providing good ventilation and avoiding exposure to direct sunlight, and protecting it from cold temperatures."),
  Item(name :"نعناع",imgpath:"asesst/imge/نعناع.jpg" , price: 13,Benefits :"Contains essential oils that help calm the body, improve digestion, and boost immunity.",Diseases_that_can_affect:"Drying out, mite infestations, viral diseases." , Treatment: "Regular watering, reducing exposure to direct sunlight, and keeping the soil moist."),

];

